version: "3"

services:
  python:
    image: python
    container_name: template-generator
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./src/python:/app
      - ./templates/technologies/wordpress:/app/templates/technologies/wordpress
    command: bash -c "pip install --upgrade pip && pip install -r requirements.txt && python main.py"
