version: "3"

services:
  builder:
    image: wp-plugin-template-builder
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-builder
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./src/python:/app
      - ./nuclei-templates/technologies/wordpress/plugins:/root/nuclei-templates/technologies/wordpress/plugins
      - ./nuclei-templates/helpers/wordpress/plugins:/root/nuclei-templates/helpers/wordpress/plugins
    command: bash -c "python3 main.py && nuclei -t technologies/wordpress/plugins -validate"
