version: "3"

services:
  builder:
    image: wp-plugin-template-builder
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-builder
    stdin_open: true
    tty: true
    working_dir: /home/runner
    volumes:
      - ./src/python:/home/runner
      - ./nuclei-templates/technologies/wordpress/plugins:/home/runner/nuclei-templates/technologies/wordpress/plugins
      - ./nuclei-templates/helpers/wordpress/plugins:/home/runner/nuclei-templates/helpers/wordpress/plugins
    command: bash -c "python3 main.py && nuclei -ud /home/runner/nuclei-templates -t ./nuclei-templates/technologies/wordpress/plugins -validate"
