
id: wordpress-child-theme-configurator

info:
  name: Child Theme Configurator Detection
  author: ricardomaia
  severity: info
  reference:
    - https://wordpress.org/plugins/child-theme-configurator/
  metadata:
    plugin_namespace: child-theme-configurator
    wpscan: https://wpscan.com/plugin/child-theme-configurator        
  tags: tech,wordpress,plugin,top-200

requests:
  - method: GET
    redirects: true
    max-redirects: 2
    path:
      - "{{BaseURL}}/wp-content/plugins/child-theme-configurator/readme.txt"
    matchers-condition: and      
    matchers:
      - type: regex
        regex:
          - '(?i)Stable.Tag'
      - type: status
        status:
          - 200
    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'
