
id: wordpress-malcare-security

info:
  name: MalCare WordPress Security Plugin – Malware Scanner, Cleaner, Security Firewall Detection
  author: ricardomaia
  severity: info
  reference:
    - https://wordpress.org/plugins/malcare-security/
  metadata:
    plugin_namespace: malcare-security
    wpscan: https://wpscan.com/plugin/malcare-security        
  tags: tech,wordpress,plugin,top-200

requests:
  - method: GET
    redirects: true
    max-redirects: 2
    path:
      - "{{BaseURL}}/wp-content/plugins/malcare-security/readme.txt"
    matchers-condition: and      
    matchers:
      - type: regex
        regex:
          - '(?i)Stable.Tag'
      - type: status
        status:
          - 200
    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'
