name: ✨ Update WordPress Plugin Templates
on:
  schedule:
    - cron: "0 4 * * *" # every day at 4am UTC
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          echo "🖥️ The workflow is now ready to test your code on the runner."
          pwd
          ls -al

      - name: Install Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: Update Templates
        run: |
          python3 .github/scripts/update-wordpress-plugin-templates.py

      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Process changes
        env:
          PUSH_TOKEN: ${{ secrets.TOKEN }}
        if: steps.changes.outputs.changed == 1
        run: |
          echo "📝 There are changes to commit."
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add *
          git commit -am "Update WordPress Plugin Templates"
          git push
