name: ✨ Update WordPress Plugin Templates
on:
  schedule:
    - cron: "0 4 * * *" # every day at 4am UTC
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Install tree
        run: sudo apt-get install tree -y

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

   
